#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_FINGERPRINT_FPC) += fpc/
obj-$(CONFIG_FINGERPRINT_CDFINGER) += cdfinger/
obj-$(CONFIG_FINGERPRINT_FOCALTECH) += focaltech/
obj-$(CONFIG_FINGERPRINT_EGISTEC) += egistec/
