# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MEDIATEK) += auto2712p1v1-ivi-boot.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += auto2712p1v1-ivi-nand-boot.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt6765.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += muse6762_64_mh55_r.dtb

